### ISSUE TITLE
Vendor folder on basic setup

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/pluginkit#4]
I'm not sure if this is the correct repo for this issue, but when following [the docs to create a basic plugin setup](https://getkirby.com/docs/guide/plugins/plugin-setup-basic#the-pluginkit-our-example-plugin), a `vendor` folder and a `composer.lock` file will be generated.

I didn't expect a `vendor` folder and was surprised by the lock file although that might be unavoidable for technical reasons.

```
Installing getkirby/pluginkit (dev-1-basic 19a16b70fc1b423abd4f921898fd1a14898704ed)
  - Installing getkirby/pluginkit (dev-1-basic 19a16b7): Cloning 19a16b70fc from cache
Created project in site/plugins/missing-link
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing getkirby/composer-installer (1.1.4): Loading from cache
Writing lock file
Generating autoload files
```

**Comment by lukasbestle** [comment]
You are right that both the `composer.lock` file and the `vendor` directory are not required for the basic Pluginkit setup (which doesn't use Composer after the original setup).

The `vendor` directory is listed in the `.gitignore` by default and therefore won't matter in practice, the `composer.lock` file is superfluous, but doesn't have much impact.

As we state in the docs:

> Please note that using Composer on the command line is not required for this tutorial, not even for supporting plugin installation via Composer. For most plugins, you can use the ZIP file of the Pluginkit and never have to touch the command line (unless you want to, which is fine too).

However I have added a note about the superfluous files to the docs.
