### ISSUE TITLE
4-Panel requires vue-template-compiler

### ISSUE THREAD

**Issue by Daandelange** [getkirby/pluginkit#9]
Hey,
Trying out the new `4-panel` setup with kirbyup, I ran `npm install` which printed : 

> npm WARN vite-plugin-vue2@1.8.2 requires a peer of vue-template-compiler@^2.2.0 but none is installed. You must install peer dependencies yourself.

`npm run dev` and `npm run build` both failed.
Fixed by : `npm install vue-template-compiler@^2.2.0 --save-dev`.
I guess it needs to be added as a dependency. (Here or in the kirbyup repo ? @johannschopplich )

Note: I also added kirbyup to the `devDependencies`, because I didn't install it globally.

**Comment by johannschopplich** [comment]
Hi there,

thanks for the bug report. The issue encountered was a problem with [kirbyup](https://github.com/johannschopplich/kirbyup). Feel free to publish an issue in the repo itself next time. 🙂 

npm 7+ automatically installs peer dependencies, whilst npm 6 and lower doesn't. Correct, the `vue-template-compiler` then is missing. I have added it to the deps list in kirbyup. Please update to kirbyup 0.14.1. Thanks!

I have added a pull request https://github.com/getkirby/pluginkit/pull/10 to raise the kirbyup version in this repo's [readme](./README.md) as well.

**Comment by bastianallgeier** [comment]
✅
